/**
 * Golden contract for IrLedger.reconcile (Q2 D: the sync-fold pass).
 *
 * Claude-authored, fenced out of the delegated scope. The oracle is an
 * in-memory VaultFs defined here. The delegated agent implements reconcile
 * in src/ir/ledger.ts ONLY and is judged solely by this suite + the rest of
 * the suite staying green + tsc. Do not edit this file to pass.
 *
 * Contract under test
 * -------------------
 *  - VaultFs gains `remove(path): Promise<void>`.
 *  - new exported constants `STATEDIR` (".ir/state") and `TOMBSTONES`
 *    (".ir/tombstones.json").
 *  - `reconcile(): Promise<LogState>` folds exactly what load() folds, then
 *    materializes that state:
 *      * one file per element at `${STATEDIR}/${element.id}.json`, holding
 *        a deterministic JSON encoding of the element (stable regardless of
 *        event arrival order; round-trips via JSON.parse to the folded
 *        element).
 *      * tombstones written to `TOMBSTONES` as a path-keyed object when any
 *        exist; the file is absent (removed if stale) when none exist.
 *      * a `${STATEDIR}/<id>.json` for an element no longer in the folded
 *        state is removed (deletion reconciliation).
 *  - Idempotent and churn-free: a reconcile that would not change a file's
 *    bytes performs no write and no remove for it (Obsidian Sync is
 *    whole-file; needless rewrites desync peers).
 *  - The returned LogState equals load().
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import {
  IrLedger,
  STATEDIR,
  TOMBSTONES,
  type VaultFs,
} from "../src/ir/ledger";
import type { LogState } from "../src/ir/log";
import {
  newElement,
  type IrEvent,
  type IrEventKind,
} from "../src/ir/model";
import {
  newElementId,
  newEventId,
  newDeviceId,
  type ElementId,
  type DeviceId,
} from "../src/ir/ids";

/** In-memory VaultFs with remove() and per-path write/remove counters. */
function memFs(): VaultFs & {
  dump(): Map<string, string>;
  writes: Map<string, number>;
  removes: Map<string, number>;
  resetCounters(): void;
} {
  const files = new Map<string, string>();
  const writes = new Map<string, number>();
  const removes = new Map<string, number>();
  const bump = (m: Map<string, number>, p: string) =>
    m.set(p, (m.get(p) ?? 0) + 1);
  return {
    dump: () => files,
    writes,
    removes,
    resetCounters() {
      writes.clear();
      removes.clear();
    },
    async exists(p) {
      return files.has(p);
    },
    async read(p) {
      const v = files.get(p);
      if (v === undefined) throw new Error(`ENOENT ${p}`);
      return v;
    },
    async write(p, data) {
      bump(writes, p);
      files.set(p, data);
    },
    async append(p, data) {
      files.set(p, (files.get(p) ?? "") + data);
    },
    async remove(p) {
      bump(removes, p);
      files.delete(p);
    },
    async list(dir) {
      const pre = dir.endsWith("/") ? dir : dir + "/";
      const out: string[] = [];
      for (const k of files.keys()) {
        if (k.startsWith(pre) && !k.slice(pre.length).includes("/")) out.push(k);
      }
      return out;
    },
  };
}

function ev(p: {
  lamport: number;
  kind: IrEventKind;
  target: ElementId;
  payload?: Record<string, unknown>;
  device?: DeviceId;
  ts?: number;
}): IrEvent {
  return {
    id: newEventId(),
    ts: p.ts ?? p.lamport * 1000,
    lamport: p.lamport,
    device: p.device ?? newDeviceId(),
    kind: p.kind,
    target: p.target,
    payload: p.payload ?? {},
  };
}

function created(id: ElementId, lamport: number): IrEvent {
  return ev({
    lamport,
    kind: "element-created",
    target: id,
    payload: { element: newElement({ id, type: "item", priority: 50, now: 0 }) },
  });
}

function statePath(id: ElementId): string {
  return `${STATEDIR}/${id}.json`;
}

async function seed(ledger: IrLedger, events: IrEvent[]): Promise<void> {
  await ledger.init();
  for (const e of events) await ledger.appendEvent(e);
}

test("reconcile materializes one file per folded element; return == load()", async () => {
  const fs = memFs();
  const ledger = new IrLedger(fs);
  const a = newElementId();
  const b = newElementId();
  const events = [
    created(a, 1),
    ev({ lamport: 2, kind: "priority-set", target: a, payload: { priority: 12 } }),
    created(b, 3),
    ev({ lamport: 4, kind: "dismiss-set", target: b, payload: { dismissed: true } }),
  ];
  await seed(ledger, events);

  const returned = await ledger.reconcile();
  const loaded = await ledger.load();
  assert.deepEqual(returned, loaded, "reconcile returns exactly the fold");

  for (const [id, el] of loaded.elements) {
    const raw = fs.dump().get(statePath(id));
    assert.ok(raw, `state file for ${id} must exist`);
    // Compare through a JSON round-trip on both sides: undefined-valued
    // optional keys (anchor/notePath on a bare item) are not data, so the
    // contract is parse-equivalence, not own-key identity.
    assert.deepEqual(
      JSON.parse(raw),
      JSON.parse(JSON.stringify(el)),
      "state file round-trips to the element",
    );
  }
  assert.equal(fs.dump().get(statePath(a)) !== undefined, true);
  assert.equal(JSON.parse(fs.dump().get(statePath(a))!).priority, 12);
  assert.equal(JSON.parse(fs.dump().get(statePath(b))!).dismissed, true);
});

test("tombstones are materialized path-keyed; absent when none", async () => {
  const fs = memFs();
  const ledger = new IrLedger(fs);
  const id = newElementId();
  const tomb = { path: "Notes/Src.md", title: "Src", deletedAt: 4242 };

  await seed(ledger, [created(id, 1)]);
  await ledger.reconcile();
  assert.equal(fs.dump().has(TOMBSTONES), false, "no tombstone file when none exist");

  await ledger.appendEvent(
    ev({ lamport: 2, kind: "source-tombstoned", target: id, payload: { tombstone: tomb } }),
  );
  await ledger.reconcile();
  const raw = fs.dump().get(TOMBSTONES);
  assert.ok(raw, "tombstone file written once a tombstone exists");
  assert.deepEqual(JSON.parse(raw)["Notes/Src.md"], tomb);
});

test("a deleted element's state file is removed on reconcile", async () => {
  const fs = memFs();
  const ledger = new IrLedger(fs);
  const a = newElementId();
  const b = newElementId();
  await seed(ledger, [created(a, 1), created(b, 2)]);
  await ledger.reconcile();
  assert.ok(fs.dump().has(statePath(a)));

  await ledger.appendEvent(ev({ lamport: 3, kind: "element-deleted", target: a }));
  await ledger.reconcile();

  assert.equal(fs.dump().has(statePath(a)), false, "deleted element file gone");
  assert.equal(fs.dump().has(statePath(b)), true, "surviving element untouched");
  const loaded = await ledger.load();
  assert.equal(loaded.elements.has(a), false);
});

test("reconcile is idempotent and churn-free", async () => {
  const fs = memFs();
  const ledger = new IrLedger(fs);
  const a = newElementId();
  const b = newElementId();
  await seed(ledger, [
    created(a, 1),
    ev({ lamport: 2, kind: "priority-set", target: a, payload: { priority: 7 } }),
    created(b, 3),
  ]);

  await ledger.reconcile();
  const snapshot = new Map(fs.dump());

  fs.resetCounters();
  const again = await ledger.reconcile();

  assert.deepEqual(fs.dump(), snapshot, "no file content changes on a no-op reconcile");
  assert.equal(
    [...fs.writes.values()].reduce((s, n) => s + n, 0),
    0,
    "zero writes when nothing changed (whole-file Sync must not churn)",
  );
  assert.equal(
    [...fs.removes.values()].reduce((s, n) => s + n, 0),
    0,
    "zero removes when nothing changed",
  );
  assert.deepEqual(again, await ledger.load());
});

test("only the changed element's file is rewritten on an incremental reconcile", async () => {
  const fs = memFs();
  const ledger = new IrLedger(fs);
  const a = newElementId();
  const b = newElementId();
  const c = newElementId();
  await seed(ledger, [created(a, 1), created(b, 2)]);
  await ledger.reconcile();

  fs.resetCounters();
  // Mutate only `a`, and introduce a brand-new element `c`.
  await ledger.appendEvent(
    ev({ lamport: 3, kind: "priority-set", target: a, payload: { priority: 99 } }),
  );
  await ledger.appendEvent(created(c, 4));
  await ledger.reconcile();

  assert.equal(fs.writes.get(statePath(a)) ?? 0, 1, "changed element rewritten once");
  assert.equal(fs.writes.get(statePath(c)) ?? 0, 1, "new element written once");
  assert.equal(fs.writes.get(statePath(b)) ?? 0, 0, "unchanged element not rewritten");
  assert.equal(JSON.parse(fs.dump().get(statePath(a))!).priority, 99);
});

test("serialization is deterministic regardless of event arrival order", async () => {
  const a = newElementId();
  const mk = () => [
    created(a, 1),
    ev({ lamport: 2, kind: "priority-set", target: a, payload: { priority: 33 } }),
    ev({ lamport: 3, kind: "dismiss-set", target: a, payload: { dismissed: true } }),
  ];

  const fs1 = memFs();
  const s1 = new IrLedger(fs1);
  await seed(s1, mk());
  await s1.reconcile();

  const fs2 = memFs();
  const s2 = new IrLedger(fs2);
  const shuffled = mk();
  await seed(s2, [shuffled[2], shuffled[0], shuffled[1]]);
  await s2.reconcile();

  assert.equal(
    fs1.dump().get(statePath(a)),
    fs2.dump().get(statePath(a)),
    "byte-identical state file for the same logical state",
  );
});
