/**
 * Golden contract for src/ir/migrate.ts (frontmatter -> store events).
 *
 * Claude-authored, fenced out of the delegated scope. Pure: no Obsidian,
 * no filesystem. The delegated agent implements src/ir/migrate.ts ONLY and
 * is judged solely by this suite + the rest of the suite staying green +
 * tsc. Do not edit this file to pass.
 *
 * Contract under test
 * -------------------
 *  - export interface FrontmatterNote { path: string;
 *      frontmatter: Record<string, unknown>; }
 *  - export function migrateNotes(notes: FrontmatterNote[], now: number):
 *      IrEvent[]
 *
 *  Every note with a valid ir-type becomes exactly one "element-created"
 *  event. The element is equivalent to what the existing pure readers
 *  decode from the same frontmatter:
 *    - priority via the model's clampPriority of ir-priority (default 50)
 *    - item  -> card = cardToStored(readCardFromFrontmatter(fm))
 *    - topic/extract -> schedule = { due, interval, aFactor } from
 *      readTopicFromFrontmatter
 *  Element ids are deterministic from the note path, so a re-run is
 *  idempotent and an ir-parent path resolves to the parent's migrated id.
 *  Migrated extracts/items are standalone notes today, so notePath is the
 *  note's own path and there is no anchor. Non-IR notes are skipped.
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import {
  elementIdForPath,
  migrateNotes,
  type FrontmatterNote,
} from "../src/ir/migrate";
import { fold } from "../src/ir/log";
import { IR_KEYS } from "../src/types";
import {
  readCardFromFrontmatter,
  cardToStored,
} from "../src/fsrs";
import { readTopicFromFrontmatter } from "../src/topic";

const NOW = 1_700_000_000_000;
const TOPIC_SETTINGS = {
  topicFirstInterval: 3,
  topicAFactor: 2,
  topicMaxInterval: 365,
};

function fm(extra: Record<string, unknown>): Record<string, unknown> {
  return { ...extra };
}

const TOPIC: FrontmatterNote = {
  path: "Sources/Paper.md",
  frontmatter: fm({
    [IR_KEYS.type]: "topic",
    [IR_KEYS.priority]: 20,
    [IR_KEYS.due]: "2026-01-01T00:00:00.000Z",
    [IR_KEYS.interval]: 9,
    [IR_KEYS.aFactor]: 2.5,
  }),
};

const EXTRACT: FrontmatterNote = {
  path: "IR/Extract A.md",
  frontmatter: fm({
    [IR_KEYS.type]: "extract",
    [IR_KEYS.priority]: 35,
    [IR_KEYS.parent]: "Sources/Paper.md",
    [IR_KEYS.due]: "2026-02-02T00:00:00.000Z",
    [IR_KEYS.interval]: 4,
    [IR_KEYS.aFactor]: 2,
  }),
};

const ITEM: FrontmatterNote = {
  path: "IR/Cloze 1.md",
  frontmatter: fm({
    [IR_KEYS.type]: "item",
    [IR_KEYS.priority]: 35,
    [IR_KEYS.parent]: "IR/Extract A.md",
    [IR_KEYS.due]: "2026-03-03T00:00:00.000Z",
    [IR_KEYS.stability]: 12.5,
    [IR_KEYS.difficulty]: 6,
    [IR_KEYS.reps]: 4,
    [IR_KEYS.lapses]: 1,
    [IR_KEYS.state]: 2,
  }),
};

const DISMISSED: FrontmatterNote = {
  path: "IR/Old.md",
  frontmatter: fm({
    [IR_KEYS.type]: "item",
    [IR_KEYS.priority]: 999, // out of range -> must clamp
    [IR_KEYS.dismissed]: true,
  }),
};

const PLAIN: FrontmatterNote = {
  path: "Daily/2026-01-01.md",
  frontmatter: fm({ tags: ["journal"] }),
};

const ALL = [TOPIC, EXTRACT, ITEM, DISMISSED, PLAIN];

test("only valid ir-type notes become elements, one created event each", () => {
  const events = migrateNotes(ALL, NOW);
  assert.equal(
    events.every((e) => e.kind === "element-created"),
    true,
    "migration emits only element-created events",
  );
  assert.equal(events.length, 4, "the non-IR note is skipped");
});

test("folded migration reproduces the frontmatter-decoded state", () => {
  const state = fold(migrateNotes(ALL, NOW).map((e) => JSON.parse(JSON.stringify(e))));
  const els = [...state.elements.values()];
  assert.equal(els.length, 4);

  const byPath = new Map(els.map((e) => [e.notePath, e]));
  const topic = byPath.get("Sources/Paper.md")!;
  const extract = byPath.get("IR/Extract A.md")!;
  const item = byPath.get("IR/Cloze 1.md")!;
  const dismissed = byPath.get("IR/Old.md")!;

  // Types and the clamp.
  assert.equal(topic.type, "topic");
  assert.equal(extract.type, "extract");
  assert.equal(item.type, "item");
  assert.equal(dismissed.priority, 100, "ir-priority 999 clamps to 100");
  assert.equal(dismissed.dismissed, true);
  assert.equal(topic.priority, 20);

  // Standalone-note mapping: own path, no anchor.
  for (const e of els) {
    assert.ok(e.notePath, "every migrated element keeps its note path");
    assert.equal(e.anchor, undefined, "migrated notes carry no block anchor");
    assert.equal(e.anchorState, "ok");
  }

  // Parent paths resolve to the parent's migrated id.
  assert.equal(extract.parentId, topic.id);
  assert.equal(item.parentId, extract.id);
  assert.equal(topic.parentId, null);

  // Item card equals the existing pure decoder's output.
  assert.deepEqual(
    item.card,
    cardToStored(readCardFromFrontmatter(ITEM.frontmatter)),
  );
  // Topic/extract schedule equals readTopicFromFrontmatter.
  const ts = readTopicFromFrontmatter(TOPIC.frontmatter, TOPIC_SETTINGS, new Date(NOW));
  assert.deepEqual(topic.schedule, {
    due: ts.dueMs,
    interval: ts.interval,
    aFactor: ts.aFactor,
  });
});

test("migration is deterministic and idempotent (safe to re-run)", () => {
  const a = migrateNotes(ALL, NOW);
  const b = migrateNotes(ALL, NOW);
  assert.deepEqual(a, b, "same input, byte-identical events (stable ids)");

  // Re-importing on top of a prior import does not fork or duplicate state.
  const once = fold(a.map((e) => JSON.parse(JSON.stringify(e))));
  const twice = fold(
    [...a, ...b].map((e) => JSON.parse(JSON.stringify(e))),
  );
  assert.deepEqual(twice, once, "re-run folds to the same state");
});

test("elementIdForPath: short paths keep the hex-of-utf8 format (backward compat)", () => {
  // Existing vaults have ids built with the original `el_mig_<hex>` scheme.
  // For any path whose hex stays well under the filename limit, the new
  // bounded encoder MUST return byte-identical output so the resolver still
  // finds migrated elements by id.
  const path = "Notes/Animals.md";
  const id = elementIdForPath(path);
  // Recompute the legacy form inline so this test fails if the encoding
  // drifts, not because we re-read a moving target.
  const bytes = new TextEncoder().encode(path);
  const hex = Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join(
    "",
  );
  assert.equal(id, `el_mig_${hex}`);
  assert.ok(id.length + ".json".length <= 255, "fits in basename budget");
});

test("elementIdForPath: long paths collapse to a bounded hash form", () => {
  // ~165-byte deeply nested path. Pre-fix this would have produced a
  // 340-char filename and crashed reconcile with ENAMETOOLONG. Post-fix
  // the id is short enough to write.
  const longPath =
    "private/sailplatform-archive/F25_AI_Technicians_Cloud_Administrator/01_Introduction_to_Cloud_Computing_Paradigm/01_CONCEPT_Cloud_Overview.md";
  const id = elementIdForPath(longPath);
  assert.ok(id.startsWith("el_mig_h_"), `expected hashed prefix, got ${id}`);
  // 7 (`el_mig_`) + 2 (`h_`) + 16 (hash) = 25 chars; plus `.json` = 30.
  assert.equal(id.length, 25);
  assert.ok(id.length + ".json".length <= 255, "fits in basename budget");
});

test("elementIdForPath: hashed form is deterministic per path", () => {
  const longPath =
    "very/deep/" + "x".repeat(200) + "/leaf.md";
  assert.equal(elementIdForPath(longPath), elementIdForPath(longPath));
});

test("elementIdForPath: distinct long paths produce distinct ids", () => {
  // Collision is astronomically unlikely (2^64), but a smoke test catches
  // a future bug where someone accidentally drops the path from the hash.
  const a = "very/deep/" + "a".repeat(200) + "/leaf.md";
  const b = "very/deep/" + "b".repeat(200) + "/leaf.md";
  assert.notEqual(elementIdForPath(a), elementIdForPath(b));
});

test("order of the input notes does not change the folded result", () => {
  const forward = fold(
    migrateNotes(ALL, NOW).map((e) => JSON.parse(JSON.stringify(e))),
  );
  const shuffled = fold(
    migrateNotes(
      [PLAIN, ITEM, TOPIC, DISMISSED, EXTRACT],
      NOW,
    ).map((e) => JSON.parse(JSON.stringify(e))),
  );
  assert.deepEqual(shuffled, forward);
});
