import sys, time, shutil; sys.path.insert(0, "/tmp")
from obs import *
exec(open('/tmp/t6.py').read().split('with sync_playwright')[0])
with sync_playwright() as pw:
    b, page = connect(pw)
    page.evaluate("() => app.plugins.disablePlugin('incremental-reading')"); time.sleep(1)
    shutil.rmtree('/tmp/ir-vault/.ir', ignore_errors=True)
    page.evaluate("() => app.plugins.enablePlugin('incremental-reading')"); time.sleep(3)
    print("plugin", plugin_state(page))
    page.evaluate("() => app.workspace.setActiveLeaf(app.workspace.getLeavesOfType('pdf')[0], {focus:true})"); time.sleep(0.5)
    page.evaluate("() => document.querySelector('.page[data-page-number=\"1\"]').scrollIntoView()"); wait_pdf(page); time.sleep(0.5)
    print("mark:", cmd(page, "incremental-reading:mark-as-ir-topic")); time.sleep(0.5)
    print("sel:", select_pdf(page, "Spaced repetition", 1)[:30]); time.sleep(0.3)
    print("extract:", cmd(page, "incremental-reading:extract-selection")); time.sleep(1.5); print(notices(page)[-1:])
    print("fresh:", fresh_review(page))
    s = goto(page, lambda s: s['pdf']); print("pdf card:", s)
    activate_review(page); time.sleep(0.5); shot(page, "30-pdf-extract-card")
    print("card selection:", select_in_body(page, "learning technique", 30)); time.sleep(0.3)
    n0 = len(notices(page))
    print("extract ->", cmd(page, "incremental-reading:extract-selection")); time.sleep(2)
    print("notices:", notices(page)[n0:], "| slot:", slot(page)); print("marks:", marks(page)); shot(page, "32-extract-from-pdf-card")
    s = goto(page, lambda s: s['file'] == 'Reading.md'); print("reading card:", s); activate_review(page)
    print("selection:", select_in_body(page, "quick", 34)); time.sleep(0.3)
    n0 = len(notices(page))
    print("extract ->", cmd(page, "incremental-reading:extract-selection")); time.sleep(2)
    print("notices:", notices(page)[n0:], "| slot:", slot(page)); print("marks:", marks(page)); shot(page, "33-reading-card-bold-extract")
